### ISSUE TITLE
Flow emulator for Go examples fails to start

### ISSUE THREAD

**Issue by kmatthews812** [onflow/flow-go-sdk#188]
### Problem

The Flow emulator fails to start in the examples directory due to an incorrect ECDSA_P256 key size.

### Steps to Reproduce 
```
➜  ~/flow-go-sdk/examples> flow emulator start -v
> invalid project configuration: input has incorrect ECDSA_P256 key size
```

Editing `flow.json` to match the schema of the config file found in the kitties-items repo allows it to start, but then the `examples.go` file fails to run. 

```
{
  "emulators": {
    "default": {
      "port": 3569,
      "serviceAccount": "emulator-account"
    }
  },
  "accounts": {
    "emulator-account": {
      "address": "f8d6e0586b0a20c7",
      "keys": "fd987817c2f796143ce97853c104b29b5e6d19747232b391033a7ddf511e355b",
      "chain": "flow-emulator"
    }
  },
  "contracts": {
    "FlowServiceAccount": "f8d6e0586b0a20c7",
    "FlowFees": "e5a8b7f23e8b548f",
    "FlowStorageFees": "f8d6e0586b0a20c7",
    "FlowToken": "0ae53cb6e3f42a79",
    "FungibleToken": "ee82856bf20e2aa6"
  }
}

```

```
➜  ~/flow-go-sdk/examples git:(master) ✗ make create-account
go run ./create_account/main.go
err: decode private key failed: the signature scheme UNKNOWN is not supported
panic: decode private key failed: the signature scheme UNKNOWN is not supported

goroutine 1 [running]:
github.com/onflow/flow-go-sdk/examples.Handle(0x194bb60, 0xc0002a4100)
	/Users/kevin/Development/searanchlabs/flow-go-sdk/examples/examples.go:243 +0xe9
github.com/onflow/flow-go-sdk/examples.ServiceAccount(0xc0002a2078, 0x0, 0xc000275d78, 0x1, 0x1)
	/Users/kevin/Development/searanchlabs/flow-go-sdk/examples/examples.go:91 +0xc5
main.CreateAccountDemo()
	/Users/kevin/Development/searanchlabs/flow-go-sdk/examples/create_account/main.go:43 +0xdb
main.main()
	/Users/kevin/Development/searanchlabs/flow-go-sdk/examples/create_account/main.go:35 +0x25
exit status 2
make: *** [create-account] Error 1
```

### Acceptance Criteria

Flow emulator starts and running `make create-account` along with other examples completes without error. 
  
### Context

It looks like the schema for `flow.json` has been updated in the emulator but not in the examples code.

**Comment by flyq** [comment]
Having the some questions:

```shell
➜  examples git:(master) flow emulator start -v
invalid project configuration: input has incorrect ECDSA_P256 key size
```

**Comment by flyq** [comment]
and 
```sh
flow emulator start --init
```
will be success. and add the service account to  the flow.json

**Comment by kmatthews812** [comment]
When I do that, the emulator starts, but the examples fail. 

```
➜  ~/Development/flow-go-sdk/examples git:(master) ✗ go run create_account/main.go
err: decode private key failed: the signature scheme UNKNOWN is not supported
panic: decode private key failed: the signature scheme UNKNOWN is not supported

goroutine 1 [running]:
github.com/onflow/flow-go-sdk/examples.Handle(0x194bb60, 0xc0005a7a40)
	/Users/kevin/Development/flow-go-sdk/examples/examples.go:243 +0xe9
github.com/onflow/flow-go-sdk/examples.ServiceAccount(0xc000593f38, 0x0, 0xc000197d78, 0x1, 0x1)
	/Users/kevin/Development/flow-go-sdk/examples/examples.go:91 +0xc5
main.CreateAccountDemo()
	/Users/kevin/Development/flow-go-sdk/examples/create_account/main.go:43 +0xdb
main.main()
	/Users/kevin/Development/flow-go-sdk/examples/create_account/main.go:35 +0x25
```

My current `flow.json` is:
```
{
        "emulators": {
                "default": {
                        "port": 3569,
                        "serviceAccount": "emulator-account"
                }
        },
        "contracts": {},
        "networks": {
                "emulator": {
                        "host": "127.0.0.1:3569",
                        "chain": "flow-emulator"
                },
                "mainnet": {
                        "host": "access.mainnet.nodes.onflow.org:9000",
                        "chain": "flow-mainnet"
                },
                "testnet": {
                        "host": "access.devnet.nodes.onflow.org:9000",
                        "chain": "flow-testnet"
                }
        },
        "accounts": {
                "emulator-account": {
                        "address": "f8d6e0586b0a20c7",
                        "keys": "4ebfa2bca119027cf6ab658dc55fcbaf4ce0482798cdb1932cdd7d17c48a497f",
                        "chain": "flow-emulator"
                }
        },
        "deployments": {}
}
```
and
```
➜  ~/Development/flow-go-sdk/examples git:(master) ✗ flow version
Version: v0.18.0
Commit: 980465a86a38f8440375c4949c54930d1019ea14
```

**Comment by psiemens** [comment]
Thanks for reporting, @kmatthews812! This should now be fixed by @moritamori's PR here: https://github.com/onflow/flow-go-sdk/pull/191

**Comment by kmatthews812** [comment]
Thank you! Works great.

**Comment by psiemens** [comment]
Don't thank me, thank @moritamori!
