### ISSUE TITLE
Emulator crash

### ISSUE THREAD

**Issue by cybercent** [onflow/flow-go-sdk#31]
## Instructions 

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem. 

### Problem

I've tried the JS wallet demo, run an example and crashed the Emulator.
I'm using the latest version of the Emulator.

### Steps to Reproduce 

I've run this code locally. The `HelloWorld` contract is not deployed.
```js
const response = await fcl.send([
    sdk.script`
	import HelloWorld from 0x02

	pub fun main() {
	    let helloAccount = getAccount(0x02)
	    let helloCapability = helloAccount.getCapability(/public/Hello)
	    let helloReference = helloCapability!.borrow<&HelloWorld.HelloAsset>()

	    log(helloReference?.hello())
	}
    `,
])
```

```sh
no code deployed at address  
panic: cannot convert value of type <nil>

goroutine 78 [running]:
github.com/onflow/cadence.convertValue(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/onflow/cadence/convert_values.go:109 +0xf71
github.com/onflow/cadence.ConvertValue(...)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/onflow/cadence/convert_values.go:33
github.com/dapperlabs/flow-emulator.(*computer).ExecuteScript(0xc0002c0740, 0xc00062c1e0, 0xc000046d40, 0x37, 0x40, 0x0, 0x5a34698, 0x0)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/dapperlabs/flow-emulator/computer.go:145 +0x548
github.com/dapperlabs/flow-emulator.(*Blockchain).ExecuteScriptAtBlock(0xc00024b220, 0xc000046d40, 0x37, 0x40, 0x0, 0x0, 0x0, 0x0)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/dapperlabs/flow-emulator/blockchain.go:624 +0x124
github.com/dapperlabs/flow-emulator/server.(*Backend).executeScriptAtBlock(0xc0002c0760, 0xc000046d40, 0x37, 0x40, 0x0, 0x4f2eca0, 0xc000310240, 0xc00006fa10)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/dapperlabs/flow-emulator/server/backend.go:429 +0x7d
github.com/dapperlabs/flow-emulator/server.(*Backend).ExecuteScriptAtLatestBlock(0xc0002c0760, 0x4f3d360, 0xc000726390, 0xc0002d6d00, 0xc0002c0760, 0x6688e38, 0xc000310240)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/dapperlabs/flow-emulator/server/backend.go:278 +0x15e
github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_ExecuteScriptAtLatestBlock_Handler.func1(0x4f3d360, 0xc000726390, 0x4cc9fa0, 0xc0002d6d00, 0x2c, 0xc0004d2230, 0x0, 0xc00006fad0)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/onflow/flow/protobuf/go/flow/access/access.pb.go:1781 +0x86
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x4f3d360, 0xc000726390, 0x4cc9fa0, 0xc0002d6d00, 0xc0007e2b20, 0xc0007e2b40, 0xc00006fb40, 0x41097b8, 0x4cbc1e0, 0xc000726390)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:107 +0xad
github.com/onflow/flow/protobuf/go/flow/access._AccessAPI_ExecuteScriptAtLatestBlock_Handler(0x4d41040, 0xc0002c0760, 0x4f3d360, 0xc000726390, 0xc00008a300, 0xc000268310, 0x4f3d360, 0xc000726390, 0xc000046d00, 0x39)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/github.com/onflow/flow/protobuf/go/flow/access/access.pb.go:1783 +0x14b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d16c0, 0x4f4d1c0, 0xc0000c2630, 0xc000362200, 0xc0002cc390, 0x5a069c0, 0x0, 0x0, 0x0)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/google.golang.org/grpc/server.go:1082 +0x4fd
google.golang.org/grpc.(*Server).handleStream(0xc0001d16c0, 0x4f4d1c0, 0xc0000c2630, 0xc000362200, 0x0)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/google.golang.org/grpc/server.go:1405 +0xd23
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000814410, 0xc0001d16c0, 0x4f4d1c0, 0xc0000c2630, 0xc000362200)
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/google.golang.org/grpc/server.go:746 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/petersiemens/go/src/github.com/dapperlabs/flow-cli/vendor/google.golang.org/grpc/server.go:744 +0xa1
```

### Acceptance Criteria

<if any>
  
### Context

Trying the JS wallet demo.

**Comment by psiemens** [comment]
Thanks for reporting, @slash7! I suspect that the JSON-CDC encoder is expecting an explicit return value from the Cadence script, which has a return type of `none`.

I'll find some time today to reproduce the error and try to confirm the source.

**Comment by psiemens** [comment]
@slash7 We were able to reproduce this and will include the fix in the next emulator release. Thanks again for reporting 🙌
