### ISSUE TITLE
Transaction crashing go sdk when calling `ID()`

### ISSUE THREAD

**Issue by austinkline** [onflow/flow-go-sdk#631]
### Problem

Transactions can crash the sdk under certain conditions if you call `Transaction.ID()`

### Steps to Reproduce 

```go
package main

import (
	"context"
	flowGrpc "github.com/onflow/flow-go-sdk/access/grpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

func main() {
	c, err := flowGrpc.NewClient(
		flowGrpc.MainnetHost,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
		grpc.WithDefaultCallOptions(grpc.MaxCallRecvMsgSize(1024*1024*1024)), // 1GB
	)
	if err != nil {
		panic(err)
	}

	ctx := context.Background()

	height := uint64(76751808)
	block, err := c.GetBlockByHeight(ctx, height)
	if err != nil {
		panic(err)
	}

	txns, err := c.GetTransactionsByBlockID(ctx, block.ID)
	if err != nil {
		panic(err)
	}

	for _, txn := range txns {
		// print the ID, one will crash
		println(txn.ID().Hex())
	}
}
```

### Acceptance Criteria

The sdk does not crash
  
### Context

Our backing ingestion system at Flowty ran into this issue.

**Comment by austinkline** [comment]
Stack Trace:

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/onflow/flow-go-sdk.(*Transaction).payloadCanonicalForm(0x1400013e6c0)
        /Users/austinkline/go/pkg/mod/github.com/onflow/flow-go-sdk@v0.44.0/transaction.go:383 +0x2a4
github.com/onflow/flow-go-sdk.(*Transaction).Encode(0x1400013e6c0)
        /Users/austinkline/go/pkg/mod/github.com/onflow/flow-go-sdk@v0.44.0/transaction.go:423 +0x3c
github.com/onflow/flow-go-sdk.(*Transaction).ID(0x140003522d0?)
        /Users/austinkline/go/pkg/mod/github.com/onflow/flow-go-sdk@v0.44.0/transaction.go:126 +0x24
main.main()
        src/crashing-block/main.go:35 +0x2c4

Process finished with the exit code 2
```

**Comment by jribbink** [comment]
It has to do with this transaction containing empty arguments when queried from AN.  https://rest-mainnet.onflow.org/v1/transactions/3b21d84b3e9c498bb1a9274793b1b3c0d590a6b9c70077b783e846ee9ee548cc

Which causes a panic when this code tries to index & position `-1` in an empty array.

https://github.com/onflow/flow-go-sdk/blob/05db7e1bbb1f23976ceadccee2072fcc9d94ea03/transaction.go#L381-L386
